ydlidar_node:
  ros__parameters:
    port: /dev/ttyUSB0    
    frame_id: lidar_link
    ignore_array: ""    
    baudrate: 128000    
    samp_rate: 5
    resolution_fixed: true
    singleChannel: true # ydlidar-x4pro
    # singleChannel: false # ydlidar-x4
    auto_reconnect: true
    reversion: true # ydlidar-x4pro
    # reversion: false # ydlidar-x4
    isToFLidar: false    
    angle_max: 180.0
    angle_min: -180.0    
    max_range: 10.0    
    min_range: 0.12    
    frequency: 10.0 
